language: node_js
node_js:
  - "12.16.1"
before_script:
  - npm install -g @angular/cli
script:
 - echo "Deploy!!"
 - npm install
 - npm run build

install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project portfolio-snahashis --token $FIREBASE_TOKEN
