name: Push on committ

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MESSAGE: "There is a new commit!"
    - uses: actions/checkout@master
    - name: whatsapp-notify
      id: whatsapp-notify
      env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          to_whatsapp_no: ${{ secrets.to_whatsapp_no }}


    - uses: atifazeez77/whatsapp-push-notify-action@master
    - name: Run
        run:|
          echo 'Start!'
